### ISSUE TITLE
[Source Request] NovelasLigeras

### ISSUE THREAD

**Issue by KasukeLp23** [rajarsheechatterjee/lnreader-sources#22]
Site: Novelasligeras.net
Spanish(ES) 

Thanks for adding

**Comment by rajarsheechatterjee** [comment]
The website is protected by captcha and the app can't bypass that. Any other sites?

**Comment by KasukeLp23** [comment]
@rajarsheechatterjee Other site in Spanish: 
https://novelasligera.com
